#! /scripts/bash
# masher interactive command

ok=1
masher=""
lettercount=0
numcount=0
noncount=0

while [ $ok -eq 1 ]
do
	echo "Please input a series of characters or * to terminate"
	read input
	if [[ $input != "" ]]
	then
		size=$[masher]

		for(( index=0; index < $size; index++ ))
		do
			character="${value:$index:1}"

			if [[ $character == "*" ]]
			then
				masher=$masher

			else if [[ $character == [[:alnum::]] ]]
			then
				lettercount=$((lettercount+1))

			else if [[ $character == [0-9] ]]
			then
				numcount=$((numcount+1))

			else if [[ $character != [[:alnum:]] ]]
			then
				noncount=$((noncount+1))
			fi
		done
	else
		ok=0
		echo "No string entered"

done

echo "You have input the string $masher"
echo "Number of letters in the string $lettercount"
echo "Numbe of digits in the string $numcount"
echo "Number of non alpha numeric characters in the string $noncount"

echo "Total number of characters in the string (including control)" #
echo "Control value at position" #
echo "Characters before control value" #

